### ISSUE TITLE
Generate component in '/src/components' folder

### ISSUE THREAD

**Issue by sentbyravens** [NetanelBasal/vue-generate-component#7]
Hello!
First of all, your plugin is very useful. 
But I don't understand how can I generate new component directly in '/src/components' folder?

'vgc -c Brands' creates Brands folder into /
'vgc -c /src/components/Brands' creates  /src/components/Brands/src/index.vue and components folder which contains Brands.component.js with name: 'src-components-brands'.

Maybe I am very stupid, but how can I achieve my goal? (All 5 files (*.html, *.js. *.scss, *.spec.js, *.vue) in /src/components/Brands folder)

**Comment by NetanelBasal** [comment]
You can navigate to the `components` folder and run `vgc -s home `

**Comment by sentbyravens** [comment]
That is what i actually did xD
But why u just don't want to place new components in 'src/components' folder by default? Isn't it best practice? (I am newbie and using Vue few days). 
Thanks for answer anyway.

**Comment by NetanelBasal** [comment]
I didn't want to enforce this.
